--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create splaysh web CFN assets"
Parameters:
  AccountArn:
    Type: String
    Description: "ARN of AWS Account. Used as value in Join"
    Default: "arn:aws:dynamodb:us-east-1:796019718156"
  EnvironmentTag:
    Type: String
    Description: Environment of the Stack
  DynamoDBTableParameter: 
    Default: "arn:aws:dynamodb:us-east-1:796019718156:table/splayshdb.dev.items" #todo paramaratize this
    Description: "Arn of the DynamoDB Table"
    Type: String
Resources: 
  splayshbrowseruser:
    Type: "AWS::IAM::User"
    Properties: 
      Path: "/functional/"
      Policies:
      - PolicyName: readtableonly
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                #- "dynamodb:BatchGetItem"
                - "dynamodb:GetItem"
                - "dynamodb:Query"
                #- "dynamodb:Scan"
              Resource:
                - Ref: DynamoDBTableParameter
                - !Join: ["/", [Ref: DynamoDBTableParameter, "index/item-nut-createdate"] ]
                #TODO- !Join: [":", [Ref: AccountArn, Ref: DynamoDBTableParameter]]
